version: '3.8' 
services:
  mms_app:
    image: "mic/mms_app:2.0.0"
    container_name: streamlit
    privileged: true
    build:
      context: .  
    volumes:
      - ./telegraf.conf:/app/telegraf.conf
      - ./config.ini:/app/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
    ports:
      - '7771:8501' 
    depends_on:
      - influxdb_mms
      - telegraf_mms

  mms_data:
    image: "mic/mms_data:2.0.0"
    container_name: mms_data
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-data
    volumes:
      - ./.env:/app/.env
      
  # mms_status_alarm:
  #   image: "mic/mms_status_alarm:2.0.0"
  #   container_name: mms_status_alarm
  #   privileged: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-status-alarm
  #   volumes:
  #     - ./.env:/app/.env

  mms_status:
    image: "mic/mms_status:2.0.0"
    container_name: mms_status
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-status
    volumes:
      - ./.env:/app/.env

  mms_alarm:
    image: "mic/mms_alarm:2.0.0"
    container_name: mms_alarm
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-alarm
    volumes:
      - ./.env:/app/.env

  auto_drop:
    container_name: auto_drop
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-autodrop
    volumes:
      - ./.env:/app/.env

  telegraf_mms:
    image: telegraf
    privileged: true
    container_name: telegraf_mms
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb_mms
    ports:
      - '8125:8125'

  influxdb_mms:
    image: influxdb:1.8-alpine
    container_name: influxdb_mms
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    env_file:
      - .env
    ports:
      - '${INFLUX_PORT}:8086'
    volumes:
      - /home/influxdb_data:/var/lib/influxdb

  ofelia:
    image: mcuadros/ofelia:latest
    privileged: true
    depends_on:
      - mms_data
      # - mms_status_alarm
      - mms_alarm
      - mms_status
    container_name: ofelia
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.ini:/etc/ofelia/config.ini

volumes:
  influxdb_data:
    driver_opts:
      type: none
      device: /home/influxdb_data
      o: bind

