FROM python:3.9-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y gnupg2 curl
RUN apt-get install -y cron \
    build-essential \
    curl \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
  && apt-get -y install gcc \
  && apt-get -y install g++ \
  && apt-get -y install unixodbc unixodbc-dev \
  && apt-get clean 
# Edit OpenSSL configuration to enable TLS 1.0
RUN sed -i 's/^\(MinProtocol =\).*/\1 TLSv1.0/' /etc/ssl/openssl.cnf

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
RUN apt install nano
CMD ["python", "autodrop.py"]