version: '3.8' 
services:
  mms_app:
    container_name: streamlit
    build:
      context: .  
    volumes:
      - ./telegraf.conf:/app/telegraf.conf
      - ./config.ini:/app/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8501:8501' 
    depends_on:
      - influxdb
      - telegraf

  mms_data:
    container_name: mms_data
    build:
      context: .
      dockerfile: Dockerfile-data

  mms_status:
    container_name: mms_status
    build:
      context: .
      dockerfile: Dockerfile-status
    restart: always

  mms_alarm:
    container_name: mms_alarm
    build:
      context: .
      dockerfile: Dockerfile-alarm
    restart: always

  telegraf:
    image: telegraf
    privileged: true
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
      - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    env_file:
      - .env
    ports:
      - '${INFLUX_PORT}:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  ofelia:
    image: mcuadros/ofelia:latest
    privileged: true
    depends_on:
      - mms_data
    container_name: ofelia
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.ini:/etc/ofelia/config.ini

volumes:
  influxdb_data: {}
