version: '3.8' 
services:
  mms_app:
    container_name: streamlit
    build:
      context: .  
    volumes:
      - ./telegraf.conf:/app/telegraf.conf
    ports:
      - '8501:8501' 
    depends_on:
      - influxdb

  telegraf:
    image: telegraf
    privileged: true
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
      - '8125:8125'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    env_file:
      - .env
    ports:
      - '${INFLUX_PORT}:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: {}
